export type USCity = { city: string; state: string };

/**
 * Major US cities covering all 50 states, sorted alphabetically.
 * Covers the primary retail markets for Whole Foods, Walmart, HEB, and Sam's Club.
 */
export const US_CITIES: USCity[] = [
  { city: "Abilene", state: "TX" },
  { city: "Akron", state: "OH" },
  { city: "Albuquerque", state: "NM" },
  { city: "Alexandria", state: "VA" },
  { city: "Allentown", state: "PA" },
  { city: "Amarillo", state: "TX" },
  { city: "Anaheim", state: "CA" },
  { city: "Anchorage", state: "AK" },
  { city: "Ann Arbor", state: "MI" },
  { city: "Arlington", state: "TX" },
  { city: "Arlington", state: "VA" },
  { city: "Atlanta", state: "GA" },
  { city: "Augusta", state: "GA" },
  { city: "Aurora", state: "CO" },
  { city: "Aurora", state: "IL" },
  { city: "Austin", state: "TX" },
  { city: "Bakersfield", state: "CA" },
  { city: "Baltimore", state: "MD" },
  { city: "Baton Rouge", state: "LA" },
  { city: "Billings", state: "MT" },
  { city: "Birmingham", state: "AL" },
  { city: "Boise", state: "ID" },
  { city: "Boston", state: "MA" },
  { city: "Boulder", state: "CO" },
  { city: "Bridgeport", state: "CT" },
  { city: "Buffalo", state: "NY" },
  { city: "Cape Coral", state: "FL" },
  { city: "Chandler", state: "AZ" },
  { city: "Charlotte", state: "NC" },
  { city: "Chattanooga", state: "TN" },
  { city: "Chicago", state: "IL" },
  { city: "Chula Vista", state: "CA" },
  { city: "Cincinnati", state: "OH" },
  { city: "Cleveland", state: "OH" },
  { city: "Colorado Springs", state: "CO" },
  { city: "Columbia", state: "SC" },
  { city: "Columbus", state: "GA" },
  { city: "Columbus", state: "OH" },
  { city: "Corpus Christi", state: "TX" },
  { city: "Dallas", state: "TX" },
  { city: "Dayton", state: "OH" },
  { city: "Denver", state: "CO" },
  { city: "Des Moines", state: "IA" },
  { city: "Detroit", state: "MI" },
  { city: "Durham", state: "NC" },
  { city: "El Paso", state: "TX" },
  { city: "Elgin", state: "IL" },
  { city: "Eugene", state: "OR" },
  { city: "Fayetteville", state: "AR" },
  { city: "Fayetteville", state: "NC" },
  { city: "Fort Collins", state: "CO" },
  { city: "Fort Lauderdale", state: "FL" },
  { city: "Fort Wayne", state: "IN" },
  { city: "Fort Worth", state: "TX" },
  { city: "Fremont", state: "CA" },
  { city: "Fresno", state: "CA" },
  { city: "Frisco", state: "TX" },
  { city: "Garland", state: "TX" },
  { city: "Gilbert", state: "AZ" },
  { city: "Glendale", state: "AZ" },
  { city: "Glendale", state: "CA" },
  { city: "Greensboro", state: "NC" },
  { city: "Hartford", state: "CT" },
  { city: "Henderson", state: "NV" },
  { city: "Hialeah", state: "FL" },
  { city: "Houston", state: "TX" },
  { city: "Honolulu", state: "HI" },
  { city: "Huntsville", state: "AL" },
  { city: "Indianapolis", state: "IN" },
  { city: "Irvine", state: "CA" },
  { city: "Irving", state: "TX" },
  { city: "Jackson", state: "MS" },
  { city: "Jacksonville", state: "FL" },
  { city: "Jersey City", state: "NJ" },
  { city: "Kansas City", state: "KS" },
  { city: "Kansas City", state: "MO" },
  { city: "Knoxville", state: "TN" },
  { city: "Laredo", state: "TX" },
  { city: "Las Vegas", state: "NV" },
  { city: "Lexington", state: "KY" },
  { city: "Lincoln", state: "NE" },
  { city: "Little Rock", state: "AR" },
  { city: "Long Beach", state: "CA" },
  { city: "Los Angeles", state: "CA" },
  { city: "Louisville", state: "KY" },
  { city: "Lubbock", state: "TX" },
  { city: "Madison", state: "WI" },
  { city: "McKinney", state: "TX" },
  { city: "Memphis", state: "TN" },
  { city: "Mesa", state: "AZ" },
  { city: "Miami", state: "FL" },
  { city: "Milwaukee", state: "WI" },
  { city: "Minneapolis", state: "MN" },
  { city: "Mobile", state: "AL" },
  { city: "Modesto", state: "CA" },
  { city: "Montgomery", state: "AL" },
  { city: "Moreno Valley", state: "CA" },
  { city: "Nashville", state: "TN" },
  { city: "New Haven", state: "CT" },
  { city: "New Orleans", state: "LA" },
  { city: "New York", state: "NY" },
  { city: "Newark", state: "NJ" },
  { city: "Norfolk", state: "VA" },
  { city: "North Las Vegas", state: "NV" },
  { city: "Oakland", state: "CA" },
  { city: "Oklahoma City", state: "OK" },
  { city: "Omaha", state: "NE" },
  { city: "Orlando", state: "FL" },
  { city: "Overland Park", state: "KS" },
  { city: "Oxnard", state: "CA" },
  { city: "Philadelphia", state: "PA" },
  { city: "Phoenix", state: "AZ" },
  { city: "Pittsburgh", state: "PA" },
  { city: "Plano", state: "TX" },
  { city: "Portland", state: "OR" },
  { city: "Providence", state: "RI" },
  { city: "Raleigh", state: "NC" },
  { city: "Reno", state: "NV" },
  { city: "Richmond", state: "VA" },
  { city: "Riverside", state: "CA" },
  { city: "Rochester", state: "NY" },
  { city: "Sacramento", state: "CA" },
  { city: "Salt Lake City", state: "UT" },
  { city: "San Antonio", state: "TX" },
  { city: "San Diego", state: "CA" },
  { city: "San Francisco", state: "CA" },
  { city: "San Jose", state: "CA" },
  { city: "Santa Ana", state: "CA" },
  { city: "Scottsdale", state: "AZ" },
  { city: "Seattle", state: "WA" },
  { city: "Shreveport", state: "LA" },
  { city: "Spokane", state: "WA" },
  { city: "St. Louis", state: "MO" },
  { city: "St. Paul", state: "MN" },
  { city: "St. Petersburg", state: "FL" },
  { city: "Stockton", state: "CA" },
  { city: "Syracuse", state: "NY" },
  { city: "Tacoma", state: "WA" },
  { city: "Tampa", state: "FL" },
  { city: "Tempe", state: "AZ" },
  { city: "Toledo", state: "OH" },
  { city: "Tucson", state: "AZ" },
  { city: "Tulsa", state: "OK" },
  { city: "Virginia Beach", state: "VA" },
  { city: "Washington", state: "DC" },
  { city: "Wichita", state: "KS" },
  { city: "Winston-Salem", state: "NC" },
  { city: "Yonkers", state: "NY" },
];

/** Returns up to `limit` cities matching the query (case-insensitive prefix or substring). */
export function searchUSCities(query: string, limit = 6): USCity[] {
  const q = query.trim().toLowerCase();
  if (q.length < 1) return [];

  const exact: USCity[] = [];
  const prefix: USCity[] = [];
  const contains: USCity[] = [];

  for (const entry of US_CITIES) {
    const cityLower = entry.city.toLowerCase();
    const label = `${entry.city}, ${entry.state}`.toLowerCase();
    if (cityLower === q || label === q) {
      exact.push(entry);
    } else if (cityLower.startsWith(q)) {
      prefix.push(entry);
    } else if (label.includes(q)) {
      contains.push(entry);
    }
    if (exact.length + prefix.length + contains.length >= limit * 2) break;
  }

  return [...exact, ...prefix, ...contains].slice(0, limit);
}
